### ISSUE TITLE
Storage space of ARM self-hosted runner is probably small

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware#13]
https://github.com/autowarefoundation/autoware/runs/4749425172?check_suite_focus=true

```
2022-01-08T18:56:43.4386749Z TASK [autoware.dev_env.ros2 : Install ros-galactic-desktop] ********************
2022-01-08T18:59:11.7105352Z ##[warning]You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 15 MB
```

Or, the capacity allocated for Docker images is too small.

**Comment by kenji-miyake** [comment]
@xmfcx Have you said that you'll change the AWS machine settings in the last meeting? I don't remember well.

**Comment by xmfcx** [comment]
> @xmfcx Have you said that you'll change the AWS machine settings in the last meeting? I don't remember well.

Yes, I'll look into it right away!

**Comment by xmfcx** [comment]
@kenji-miyake 
Here is the report:

[autowarefoundation](https://github.com/autowarefoundation) organization has a [GitHub Actions Runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) registered with a name `AutowareFoundationGithubActionsRunner`.

This runner runs on an AWS `t4g.xlarge` instance. [Amazon EC2 T4g instances are powered by Arm-based AWS Graviton2 processors.](https://aws.amazon.com/ec2/instance-types/t4/)

It has 4 vCPUs and 16GiB RAM.

This binary was installed on it: https://github.com/actions/runner/releases/download/v2.276.1/actions-runner-linux-arm64-2.276.1.tar.gz

```bash
ubuntu@ip-192-168-22-5:~$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        29G   25G  4.4G  85% /
```

<details>
  <summary>Having fun with ncdu inside the runner</summary>
  
```
ncdu 1.14.1 ~ Use the arrow keys to navigate, press ? for help
--- / -------------------------------------------------------------------------------------------------------------------
   17.4 GiB [##########] /var
    4.5 GiB [##        ] /usr
    2.0 GiB [#         ] /snap
    1.9 GiB [#         ] /home
  273.0 MiB [          ] /opt
  191.8 MiB [          ] /boot
   69.0 MiB [          ] /root
    5.9 MiB [          ] /etc
    1.0 MiB [          ] /run
  600.0 KiB [          ] /tmp
...
```

```
--- /var ----------------------------------------------------------------------------------------------------------------
                         /..
   16.5 GiB [##########] /lib
  838.5 MiB [          ] /log
   91.6 MiB [          ] /cache
    3.8 MiB [          ] /backups
   92.0 KiB [          ] /snap
   32.0 KiB [          ] /tmp
   28.0 KiB [          ] /spool
e   4.0 KiB [          ] /opt
...
```

```
--- /var/lib ------------------------------------------------------------------------------------------------------------
                         /..
   15.4 GiB [##########] /docker
  929.7 MiB [          ] /snapd
  122.9 MiB [          ] /apt
   71.5 MiB [          ] /dpkg
    2.8 MiB [          ] /command-not-found
  872.0 KiB [          ] /fwupd
  608.0 KiB [          ] /usbutils
  532.0 KiB [          ] /systemd
...
```

```
--- /var/lib/docker/overlay2 --------------------------------------------------------------------------------------------
                         /..
    2.0 GiB [##########] /3f789e1ccb84eced273bbd5ec673d26bf2ba73badea2366fb5ce7c1e455deb3c
    1.7 GiB [########  ] /860d068134bb56e762666ace5f4f4e8776a54d2a4bd4dadaa213903dd36e1e8a
    1.6 GiB [#######   ] /961ad94a1a2d8bde97c3e7a4fd920b32dea466dee7a2e798cbd0cd9de3b9579c
    1.2 GiB [######    ] /oz9h7z6ksun9pzg6s52do34bs
    1.2 GiB [######    ] /igc3ivk7fko8yv0dy5f3ix6es
    1.1 GiB [#####     ] /acf011033a08512ba500bb9cb491c8fe2b85800fd51f5940688dacaae258b347
    1.0 GiB [####      ] /k39z3vtovy72t3rd9kul7ylts
    1.0 GiB [####      ] /ocnfwy30dy9qn4iv197j3wx32
  971.0 MiB [####      ] /ozlaq5qbqyl4vrp20vymjja8v
  764.8 MiB [###       ] /mk3870wqhylwvxem7ortmtvfm
  555.1 MiB [##        ] /75e02708a769eec5b19605086f65f8db2bad1cd2cc855134b7d7a5228e33f8ab
  379.1 MiB [#         ] /b466a752974568564c50ef30c00e5aa5c481241400098aec28cb965b4367d66e
  360.7 MiB [#         ] /7df0aabea828669c65dfc3d6c5fa1b2512eeb4beb2d7b985043a7fca7c5a90f9
  360.6 MiB [#         ] /19f37636febdd3ad4e677c761f54a18bcc406ef569a56c915a462b492a5b00d9
  170.9 MiB [          ] /8bfa3d5126374b0ff2bf1b5dbbd2b9b2c7250c85f8b0110c4e2cab8c3aee7acc
  170.9 MiB [          ] /c3ca31b9a7ce3931b2f9887e59374a97f5261c794a8f3c2c5eb0d091f30ed8e3
  121.5 MiB [          ] /28e5f0a7ef59844e7d1303e8207c0fe4f1d6b999e25ef0457e63d5634c2ee0d2
  108.3 MiB [          ] /b3e692e697ed02bc6c1f220ef9f222e6fd31f3b703f33787ea236671249ebdbe
  103.1 MiB [          ] /669a56810f2f0b641ee12f378861f98bb2e95a3feddeed03fff75a219e234ef8
   71.1 MiB [          ] /2698239224b14e3b7c4b8ae829c555b9baa308379f372d0834fe61b0b723d3f6
   71.1 MiB [          ] /98f54927abe28c6547dc7d3dc0796adfb3f2a8605b3c95fb9dbcf552f32cb071
   71.1 MiB [          ] /df580563836e90306194f98a714a4a3fa843731b35da05fe125d55e6ea714c4e
   71.1 MiB [          ] /03e58f58a62ce5c1b373555c209ad5484763751c6acad9363c85762e12d9116f
   67.2 MiB [          ] /d16b246099269bcd9dc49a24bd702f8a390070c47ddf063dd0a6b722e94f62cb
...
```
</details>

Then I ran:
```

ubuntu@ip-192-168-22-5:~$ docker images
REPOSITORY                   TAG                       IMAGE ID       CREATED        SIZE
ros                          galactic                  775c4b4329a0   7 days ago     625MB
ubuntu                       20.04                     9f4877540c73   7 days ago     65.6MB
autoware/model-zoo-tvm-cli   bleedingedge              2c1d92d7cf06   6 weeks ago    3.32GB
autoware/model-zoo-tvm-cli   bleedingedge-arm64        2c1d92d7cf06   6 weeks ago    3.32GB
autoware/model-zoo-tvm-cli   bleedingedge-cuda         051076320a77   6 weeks ago    7.1GB
autoware/model-zoo-tvm-cli   bleedingedge-cuda-arm64   051076320a77   6 weeks ago    7.1GB
moby/buildkit                buildx-stable-1           cb9b18fdb708   8 weeks ago    134MB
ros                          <none>                    d1dc7d553def   3 months ago   624MB
autoware/model-zoo-tvm-cli   <none>                    23e209b2f626   3 months ago   4GB

```

These docker images are occupying a lot of space.

They are generated by the runner probably, there are nothing related to them in the .bash_history file.

Then I've proceed to clean them a bit.

```bash
ubuntu@ip-192-168-22-5:~$ docker image prune
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N] y
Deleted Images:
untagged: autoware/model-zoo-tvm-cli@sha256:a7831a40332f75ae98fb62a04f75ad2db6a6fbf8fafc409d0f69e95abc41dcb9
deleted: sha256:23e209b2f626500be6d8854fd1010229fca6f51876db4c63d3fd4851a536b7c0
deleted: sha256:dbafe75a3ee1ece980197b9886402ce3e1524b29bfbc1963690305488f81a0d7
deleted: sha256:7619c374c847a8893d3c85d6dca6202a90beb171237b3451ee0b5181c5a59b75
deleted: sha256:77ff28323bd0da84f6229138b3307e1ecfde62ebde42918feb7a8b52b95d5122
deleted: sha256:77fee4372c0621a932345c0288736a71ea21caf9a383c29aa017d137e2e07bc5
deleted: sha256:08e85464003280159ce7fd6cf708da6b67223505ff318307928375684e4dee3c
deleted: sha256:df4dcf3f56b841655e03092b79a66b996bbb9335b4151f55e9a1a73c10f18d71
deleted: sha256:1f4e146407f3bb98c8b661348e00af043449d5ad10242ccedde70d711badabbb
deleted: sha256:35acadea3b5a2a96f4b2f4c74ed894b3ba914a3f4d5d3c7a229791494e49bedc
deleted: sha256:7b8728eb6a07380fce7ee9581ed43d58d7f0f3250c50a44c38c7982536236e28
deleted: sha256:c9115e738038f017bc9cbaea0a25b42921263d79199b1133b964633162b0d843
deleted: sha256:1093f8b99677a049c1627342e2632c7d060f4cd058fec56a22c52ac358887570
deleted: sha256:bed5eaa83dce8f654fd931ac6b1c4de67fef4482b3270a5d98ae901a4b48d35e
deleted: sha256:4378b6ba3aa966c9d3d45efb1c97a87a79e2ccae62acf898e20ab7712b254726
deleted: sha256:cf1297c9d105cb8049c0f02f12a3c5a1c7c679f30a1de64c5f97b4c006cdc564
deleted: sha256:7a0d5c3393a6fb45b7436dee209a214e1d7d3497b4ed11c963c0de19c2173b3d
deleted: sha256:68d7ba65f4836161cd7e568374ad6eb90a1fbdbd807691f47b55dfd85222910e
deleted: sha256:942b063c301eb3a3581299227847df70c896991a18216541c4bafb41a4263ffb
untagged: ros@sha256:65beaaee344167f62b4ff87373d84faa27e1ea73b5de15f1a59646bea87de4d2
deleted: sha256:d1dc7d553defc3476d6d036001a2ebef1c69198b71864342ba12919988328c4a
deleted: sha256:fcb03701ef491fd30f750ea7c0697219e7efb79499394da89af966fb7f973991
deleted: sha256:108a51d95fa73e3c488d196b6c0e05e502746f88fd19a9f01f417044673f5e89
deleted: sha256:30dfd34b65d0c2cdf59cce36ff380adf6e01d41441d39824cea4b1407e060169
deleted: sha256:c23e51d5095f6c9180648792b4036e4538b51eeee815628885a23ca76ed04195
deleted: sha256:77f7733c23042efa6d253941dc786e0fe7b641e7622d1ec9b215e9ef8abcd743
deleted: sha256:e52184f9949df47092392cb61725debef580d6d20cb86518da7a98b946967c8a
deleted: sha256:19553373bc3b429fbfedb19ee24f9335856b7f0ed8beea7baaed31767a784bb9
deleted: sha256:d4ebf66ca37317b8fcd9ca3450e2707674b947c5f1751f62894e6869c0120343
deleted: sha256:0d590595a73a77a32952a1ac40fc91c8a0c7b965059e22f89deaac010c951d4b
deleted: sha256:12ebadd02095a97092b2327a681c7beffc761f73c544e077967f88f8388807f4

Total reclaimed space: 4.557GB

ubuntu@ip-192-168-22-5:~$ docker images
REPOSITORY                   TAG                       IMAGE ID       CREATED       SIZE
ros                          galactic                  775c4b4329a0   7 days ago    625MB
ubuntu                       20.04                     9f4877540c73   7 days ago    65.6MB
autoware/model-zoo-tvm-cli   bleedingedge              2c1d92d7cf06   6 weeks ago   3.32GB
autoware/model-zoo-tvm-cli   bleedingedge-arm64        2c1d92d7cf06   6 weeks ago   3.32GB
autoware/model-zoo-tvm-cli   bleedingedge-cuda         051076320a77   6 weeks ago   7.1GB
autoware/model-zoo-tvm-cli   bleedingedge-cuda-arm64   051076320a77   6 weeks ago   7.1GB
moby/buildkit                buildx-stable-1           cb9b18fdb708   8 weeks ago   134MB

ubuntu@ip-192-168-22-5:~$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        29G   20G  9.0G  70% /

```

Now we have 9.0G space left. I could remove these images too but they would get redownloaded anyway probably.

We probably look into https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners for autoscaling since right now all arm jobs go into this specific runner.

**Comment by xmfcx** [comment]
Also for x86_64 jobs we are using [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners):

![chrome_2022-01-14_21-12-13](https://user-images.githubusercontent.com/10751153/149564595-be89d035-18b0-478c-ae7b-1ae14b96fe9a.png)

Hardware specification for Windows and Linux virtual machines:

2-core CPU
7 GB of RAM memory
14 GB of SSD disk space
 
And I think these machines probably won't be enough for building the Autoware and we will need to look into self-hosted ephemeral runners for these too.

**Comment by kenji-miyake** [comment]
@xmfcx Thank you for your detailed report!

> Now we have 9.0G space left. I could remove these images too but they would get redownloaded anyway probably.

Hmm, it's too small... :cry: 
I want at least 30GB of free space, is it possible to extend the storage size of the VM?

> Hardware specification for Windows and Linux virtual machines:

Regarding GitHub-hosted runners, I guess it's minimum requirements.
The actual storage space can be seen [here](https://github.com/autowarefoundation/autoware/runs/4777125097?check_suite_focus=true#step:3:23).

> And I think these machines probably won't be enough for building the Autoware and we will need to look into self-hosted ephemeral runners for these too.

Anyway, if there's no problem with the cost, it's nice.

**Comment by xmfcx** [comment]
> @xmfcx Thank you for your detailed report!
> 
> > Now we have 9.0G space left. I could remove these images too but they would get redownloaded anyway probably.
> 
> Hmm, it's too small... 😢 I want at least 30GB of free space, is it possible to extend the storage size of the VM?

I've increased the storage by 30GB, now we have 39GB empty space.

```bash
ubuntu@ip-192-168-22-5:~$ df -h
Filesystem       Size  Used Avail Use% Mounted on
/dev/root         58G   20G   39G  35% /
```

**Comment by kenji-miyake** [comment]
I confirmed that the CI is fixed in https://github.com/autowarefoundation/autoware/pull/8#issuecomment-1015132292.

Thank you @xmfcx !

**Comment by kenji-miyake** [comment]
@xmfcx I'm sorry but it seems we need a bit more space. :cry: 
https://github.com/autowarefoundation/autoware/actions/runs/1712036308

Seeing this result, we need 55GB+ free space? :thinking: 
https://github.com/autowarefoundation/autoware/actions/runs/1683139813
https://github.com/autowarefoundation/autoware/runs/4777125097?check_suite_focus=true#step:3:1110

> docker-build-and-push-amd64
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 36 MB

> Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   30G   55G  35% /

I'll investigate more.

**Comment by kenji-miyake** [comment]
I measured the storage usage before/after building Autoware Docker images. It used `44GB` for `amd64`.
https://github.com/autowarefoundation/autoware/runs/4857291024?check_suite_focus=true

![image](https://user-images.githubusercontent.com/31987104/150050900-c916e293-9a2a-412b-9d3f-1841f86a6b53.png)

**Comment by kenji-miyake** [comment]
@xmfcx Is it possible to add more 10~20GB space...?

**Comment by xmfcx** [comment]
> @xmfcx Is it possible to add more 10~20GB space...? Or if we drop building `prebuilt` images, probably the current space is enough.

We could add but I think we should first try to reduce the space we are using. This is ok for single runner but for parallel runners it'll cost too much, not scalable. In autoware.auto 30gb total space for entire machine was enough.

**Comment by kenji-miyake** [comment]
> We could add but I think we should first try to reduce the space we are using.

What do you think we can specifically do in order to save the space?

> In autoware.auto 30gb total space for entire machine was enough.

Yes, but the current `autoware.universe` depends on CUDA, which uses additional 10GB+. :cry:

**Comment by xmfcx** [comment]
We won't use cuda on CI, we should make it optional.

**Comment by kenji-miyake** [comment]
If so, we can't check the build of some perception modules in `autoware.universe`, is that okay?

**Comment by xmfcx** [comment]
> If so, we can't check the build of some perception modules in `autoware.universe`, is that okay? Also, could you tell me why do you think making it optional is good?

The CI machines don't have Nvidia gpus and CUDA only works on nvidia gpus so we couldn't check them anyway.

Instances with gpus are much more expensive, we could set them to be checked with lower frequency if needed.

**Comment by kenji-miyake** [comment]
@xmfcx 
> The CI machines don't have Nvidia gpus and CUDA only works on nvidia gpus so we couldn't check them anyway.

Yes, we can't check the runtime behavior, but I think we can check the build.

> Instances with gpus are much more expensive, we could set them to be checked with lower frequency if needed.

We don't need GPUs.

**Comment by kenji-miyake** [comment]
@xmfcx So considering that, can we increase the space or cannot in any case?

**Comment by xmfcx** [comment]
@kenji-miyake right now it has 60GB size, will increase it to 80GB. Since it is only a single machine, it shouldn't be a problem hopefully.

**Comment by xmfcx** [comment]
@kenji-miyake Increased it, current configuration:
```bash
Filesystem       Size  Used Avail Use% Mounted on
/dev/root         78G   46G   33G  59% /
```

**Comment by kenji-miyake** [comment]
Thank you! But it seems there is another issue... :cry: I'll investigate and fix it.
https://github.com/autowarefoundation/autoware/actions/runs/1714127510

**Comment by kenji-miyake** [comment]
```
root@ip-192-168-22-5:/var/lib/docker# du -sh *
1.6M    buildkit
244K    containers
26M     image
76K     network
24G     overlay2
16K     plugins
4.0K    runtimes
4.0K    swarm
6.8G    tmp
4.0K    trust
38G     volumes
```

**Comment by xmfcx** [comment]
> ```
> root@ip-192-168-22-5:/var/lib/docker# du -sh *
> 1.6M    buildkit
> 244K    containers
> 26M     image
> 76K     network
> 24G     overlay2
> 16K     plugins
> 4.0K    runtimes
> 4.0K    swarm
> 6.8G    tmp
> 4.0K    trust
> 38G     volumes
> ```

Yeah, I've also stated it in https://github.com/autowarefoundation/autoware/issues/13#issuecomment-1013343067 in collapsed logs.

**Comment by kenji-miyake** [comment]
Oh, yes it was folded, sorry.

And after `docker system prune --all`

```
root@ip-192-168-22-5:/var/lib/docker# du -sh *
1.6M    buildkit
244K    containers
3.1M    image
76K     network
906M    overlay2
16K     plugins
4.0K    runtimes
4.0K    swarm
4.0K    tmp
4.0K    trust
24G     volumes
```

**Comment by kenji-miyake** [comment]
@xmfcx Succeeded!
https://github.com/autowarefoundation/autoware/runs/4870569220?check_suite_focus=true

I'll try some more times to confirm there isn't an old and big cache left.
