### ISSUE TITLE
[Docker] Edit files on host and execute on a container 

### ISSUE THREAD

**Issue by IshitaTakeshi** [autowarefoundation/autoware#23]
I'd like to propose the improvement on Dockerfile to modify the code on the host environment rather than on a container. 

[Current Dockerfile on the add-docker branch](https://github.com/autowarefoundation/autoware/blob/add-docker/docker/autoware-universe/Dockerfile) expects to modify the code on a container rather than the host. But it is inefficient to set up the development environment and change the code on a container. 
So I propose modifying the files on the host, mounting `src` on a container, and running autoware on the container.

**Comment by kenji-miyake** [comment]
@IshitaTakeshi We prepare two images `devel` and `prebuilt`. I think using `devel` image can solve your problem. Is it okay for you?

https://github.com/autowarefoundation/autoware/tree/add-docker/docker#development-image

**Comment by IshitaTakeshi** [comment]
For the development I think that the mount procedure should be written in README or we should add a script to realize it.

**Comment by IshitaTakeshi** [comment]
Still there are other updates to the docker environment and I have my personal tasks so let me show my launch command this time. 

```
rocker \
    --nvidia \
    --x11 \
    --volume $(pwd)/dataset:/dataset \
    --volume $(realpath src):/autoware \
    -- ghcr.io/autowarefoundation/autoware-universe:latest-prebuilt
```

**Comment by kenji-miyake** [comment]
@IshitaTakeshi I updated the document, could you review it?
https://github.com/autowarefoundation/autoware/pull/14
https://github.com/autowarefoundation/autoware/pull/14/commits/6958e38ff15a2cea20f205d384a47c3574f75052

**Comment by IshitaTakeshi** [comment]
Commands look good. Can I overwrite the English text part?

**Comment by kenji-miyake** [comment]
@IshitaTakeshi Actually refrain from that, please propose changes instead. :pray: 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request

**Comment by kenji-miyake** [comment]
@IshitaTakeshi Is it okay for you to close this issue?

**Comment by IshitaTakeshi** [comment]
Yes. Thank you for commiting
