### ISSUE TITLE
Support ROS 2 Rolling on Ubuntu 22.04

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware#238]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

ROS 2 Humble will be released this May.
https://docs.ros.org/en/rolling/Releases/Release-Humble-Hawksbill.html

To smoothly transit to Humble, it's good to support Rolling before that.

Related: https://github.com/autowarefoundation/autoware.universe/issues/268

### Purpose

To smoothly transit to Humble.

### Possible approaches

Replace all Galactic-dependent parts with the new styles.

### Definition of done

Autoware's tutorials work with ROS 2 Rolling on Ubuntu 22.04.

**Comment by kenji-miyake** [comment]
@xmfcx @mitsudome-r @esteve I'll work on this with the help of @wep21.

**Comment by esteve** [comment]
@kenji-miyake let me if there's anything I can help with, I'm happy to contribute code and review PRs.

**Comment by kenji-miyake** [comment]
Since Humble is already available with `ros2-testing`, I'll test it, too.
https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html

**Comment by kenji-miyake** [comment]
I'll support Humble in another branch/PR.
