### ISSUE TITLE
[Docker] Autoware.universe requires kvaser-interface

### ISSUE THREAD

**Issue by IshitaTakeshi** [autowarefoundation/autoware#25]
[The current Dockerfile](https://github.com/autowarefoundation/autoware/blob/add-docker/docker/autoware-universe/Dockerfile) doesn't install kvaser-interface even autoware.universe requires it 

To install kvaser-interface we need to explicitly add the repository as in the [installation procedure](https://github.com/astuff/kvaser_interface#installation) so we need to update the ansible playbook

**Comment by kenji-miyake** [comment]
@IshitaTakeshi Please describe for what reasons you need `kvaser-interface`.
Also, is it impossible to replace it with https://github.com/autowarefoundation/ros2_socketcan?

It seems Kvaser devices supports SocketCAN.
https://www.kvaser.com/socketcan-support-for-kvaser-devices-updated/

**Comment by wep21** [comment]
We have never used `ros2_socketcan` on autonomostuff vehicle, so we have to test on the real vehicle before migrating to `ros2_socketcan`.

**Comment by kenji-miyake** [comment]
Okay, then I think we should test it. If it won't work we'll import the role from here.
https://github.com/tier4/AutowareArchitectureProposal.proj/blob/474da436880f93bd59d87107bd9d83254b0cd9b3/ansible/roles/pacmod/tasks/kvaser_library.yml

**Comment by wep21** [comment]
Also we have to do a trick to use kvaser usb as socketcan.
```
sudo modprobe kvaser_usb
<- unplug and plug kvaser usb here
sudo ip link set can0 up type can bitrate 50000
```

**Comment by kenji-miyake** [comment]
Thank you. I think it can be supported by some setup scripts for real vehicles.

**Comment by IshitaTakeshi** [comment]
This is the reason to add kvaser-interface to the requirements. When launching the logging simulator it says that kvaser_interface cannot be found.

```
root@87a3663a4a81:/autoware# source install/setup.bash 
root@87a3663a4a81:/autoware# ros2 launch tier4_autoware_launch logging_simulator.launch.xml sensor_model:=aip_xx1 map_path:=/dataset/kashiwanoha/ vehicle_model:=lexus
[INFO] [launch]: All log files can be found below /root/.ros/log/2022-01-19-09-21-13-992999-87a3663a4a81-60
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=PackageNotFoundError("package 'kvaser_interface' not found,
```

**Comment by kenji-miyake** [comment]
Why do you need `kvaser-interface` for the launch file?
Do you use a physical CAN in the simulation?

**Comment by IshitaTakeshi** [comment]
Not sure so I grep-ed in the workspace directory and got the following

```
# find . -type f | xargs grep kvaser_interface
./src/vehicle/lexus_launch/launch/pacmod3.launch.py:            package='kvaser_interface',
./install/lexus_description/share/lexus_description/launch/pacmod3.launch.py:            package='kvaser_interface',
```

Apparently pacmod3 requires it.

**Comment by kenji-miyake** [comment]
I know it has the dependency, but my question is, why do you have to launch the node in the simulation?

**Comment by IshitaTakeshi** [comment]
What node do you refer to?

My current task is to improve the localization accuracy and availability so basically I don't need to launch all the nodes under the logging simulator, but for me, who doesn't know that much about the Autoware architecture, it is easier to launch the logging simulator than disabling unnecessary nodes.

**Comment by kenji-miyake** [comment]
> What node do you refer to?

Probably this?
https://github.com/tier4/lexus_description.iv/blob/4a3a06e297f85a737d2b5879b508843b2998038a/launch/pacmod3_with_kvaser-node-launch.py

> but for me, who doesn't know that much about the Autoware architecture,

I believe it's better that you'll get familiar with Autoware and do appropriate handling!
I guess, for example, we need to add an option of whether to launch `kvaser-interface`, to [this file](https://github.com/tier4/lexus_description.iv/blob/4a3a06e297f85a737d2b5879b508843b2998038a/launch/vehicle_interface.launch.xml).

**Comment by IshitaTakeshi** [comment]
Okay, but at least as an OSS it should be much better the logging simulator always works fine so when merging the Dockerfile to the default branch we should disable the node depending on `kvaser-interface` (or install `kvaser-interface`).

**Comment by kenji-miyake** [comment]
@IshitaTakeshi Regarding that, I believe we should consider replacing `kvaser-interface` by `ros2_socketcan`.
https://github.com/autowarefoundation/autoware/issues/25#issuecomment-1015268018

Please understand that adding everything isn't always correct.

**Comment by kenji-miyake** [comment]
Acceptance Criteria:

- [ ] Consider replacing `kvaser-interface` by `ros2_socketcan`.
We need to evaluate `ros2_socketcan` with Kvaser devices to do that.

Or,
- [ ] Consider removing `kvaser-interface` from `logging_simulator.launch.xml`.
Essentially, no hardware is required for the simulation.

**Comment by xczhanjun** [comment]
> Acceptance Criteria:
> 
> * [ ]  Consider replacing `kvaser-interface` by `ros2_socketcan`.
>   We need to evaluate `ros2_socketcan` with Kvaser devices to do that.
> 
> Or,
> 
> * [ ]  Consider removing `kvaser-interface` from `logging_simulator.launch.xml`.
>   Essentially, no hardware is required for the simulation.
Maybe we should remove `kvaser-interface` from `logging_simulator.launch.xml` and using ros2_socketcan. We can setup a fake socket can interface when doing simulation.
