### ISSUE TITLE
Fail to update a workspace

### ISSUE THREAD

**Issue by shmpwk** [autowarefoundation/autoware#263]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I'm following [How to update a workspace](https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/#how-to-update-a-workspace).
In order to update repos, it says we command
```
vcs import src < autoware.repos
vcs pull
```
However, it seems it ignores under `src` directory because of `.gitignore`.
Thus we should command as follows?
```
vcs import src < autoware.repos
vcs pull src
```

### Expected behavior

Updating repos by `vcs pull` 

### Actual behavior

No repos updated by `vcs pull`

### Steps to reproduce

Follow [How to update a workspace](https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/#how-to-update-a-workspace)

**Comment by kenji-miyake** [comment]
@shmpwk Ah, yeah exactly. I'm sorry for my mistake. :bow: 
Could you fix send a PR to fix this? :pray: 

> because of .gitignore.

Strictly speaking, I believe `.gitignore` isn't related. It's because `~/autoware` is a Git repository. So you can also use `vcs pull --nested` to update the workspace.

**Comment by shmpwk** [comment]
Thank you, I see.
Which do you lilke `vcs pull src` or `vcs pull --nested`?

**Comment by shmpwk** [comment]
I've use former.
Close by https://github.com/autowarefoundation/autoware-documentation/pull/95

**Comment by kenji-miyake** [comment]
Thank you for your PR!
I personally prefer `vcs pull src` because I've never used the `--nested` option.
