### ISSUE TITLE
Run setup-dev-env.sh docker failed

### ISSUE THREAD

**Issue by Sharrrrk** [autowarefoundation/autoware#272]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

When I run setup-dev-env.sh docker for the first time, the following error occurs:

```
nv@xavier-5:~/ws/autoware$ ./setup-dev-env.sh docker
Setting up the build environment take up to 1 hour.
>  Are you sure to run the setup? [y/N] y
./setup-dev-env.sh: line 105: ansible-galaxy: command not found
```

### Expected behavior

The script should run without error

### Actual behavior

Error occured and stopped.

### Steps to reproduce

1. CLone project
2. Run `./setup-dev-env.sh docker`

### Versions

- OS: Ubuntu 20.04
- ROS2: Galactic
- Autoware: main

### Possible causes

ansible was previously installed under user account, but not under root account. This may cause the version check to pass, but ansible-galaxy not found by root account.

**Comment by kenji-miyake** [comment]
@Sharrrrk Thank you for reporting this.
- What's your Ansible version?
https://github.com/autowarefoundation/autoware/blob/af25faddd16bf8f9a1bace814b0f82e020803f5b/setup-dev-env.sh#L98-L99
- Is `$HOME/.local/bin` in your PATH?

**Comment by Sharrrrk** [comment]
@kenji-miyake I was just updating my description, yes you are right, ansible is installed by a user account, not root account. But the version check passes.

**Comment by kenji-miyake** [comment]
@Sharrrrk I see, thank you. Could you update the script to work in your environment? Or should I help something?

**Comment by kenji-miyake** [comment]
By the way, I'm thinking of removing `sudo` from `pip` install. 92c356754133b8414d5a0feef04fb51227547bda
Is that related to this issue?

**Comment by Sharrrrk** [comment]
> 

I can quick fix it with `sudo pip3 install ansible`. 

>By the way, I'm thinking of removing sudo from pip install. 

This definitely would solve this issue. Thank you.
