### ISSUE TITLE
build faild

### ISSUE THREAD

**Issue by mengmenghu211** [autowarefoundation/autoware#276]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

--- stderr: traffic_light_classifier
CMake Error at ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:100 (message):
  ament_cmake_symlink_install_directory() can't find
  '/home/liutieshan/autoware/src/universe/autoware.universe/perception/traffic_light_classifier/data'
Call Stack (most recent call first):
  ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:332 (ament_cmake_symlink_install_directory)
  cmake_install.cmake:41 (include)

### Expected behavior

--- stderr: traffic_light_classifier
CMake Error at ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:100 (message):
  ament_cmake_symlink_install_directory() can't find
  '/home/liutieshan/autoware/src/universe/autoware.universe/perception/traffic_light_classifier/data'
Call Stack (most recent call first):
  ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:332 (ament_cmake_symlink_install_directory)
  cmake_install.cmake:41 (include)

### Actual behavior

--- stderr: traffic_light_classifier
CMake Error at ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:100 (message):
  ament_cmake_symlink_install_directory() can't find
  '/home/liutieshan/autoware/src/universe/autoware.universe/perception/traffic_light_classifier/data'
Call Stack (most recent call first):
  ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:332 (ament_cmake_symlink_install_directory)
  cmake_install.cmake:41 (include)

### Steps to reproduce

--- stderr: traffic_light_classifier
CMake Error at ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:100 (message):
  ament_cmake_symlink_install_directory() can't find
  '/home/liutieshan/autoware/src/universe/autoware.universe/perception/traffic_light_classifier/data'
Call Stack (most recent call first):
  ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:332 (ament_cmake_symlink_install_directory)
  cmake_install.cmake:41 (include)

**Comment by shmpwk** [comment]
If you can describe 
- your version of OS , cuda version, cudnn, TensorRT and etc,
- the command the error reproduced
we are very helpful since we can share the problem.
