### ISSUE TITLE
Set up scenario testing CI

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware#28]
As pointed out [here](https://github.com/autowarefoundation/autoware/pull/26#issuecomment-1016010614), it's useful if we can run scenario testing on CI.

We can use TIER IV's Autoware Evaluator for this use case.
In that case, we need to add `.webauto-ci.yml` to this repository.
https://github.com/tier4/AutowareArchitectureProposal.proj/blob/474da436880f93bd59d87107bd9d83254b0cd9b3/.webauto-ci.yml
https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/635b36e0b461f66f25fd4a9c30231ca5f129e5db/.webauto-ci.yml

**Comment by xczhanjun** [comment]
this is a great feature.

**Comment by kenji-miyake** [comment]
Closed by #397.
