### ISSUE TITLE
Consider how we should write copyright notices

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware#30]
Opened by this comment: https://github.com/autowarefoundation/autoware/pull/29#discussion_r790972404

Reference links:
- https://opensource.google/docs/copyright/#the-year
- https://www.linuxfoundation.org/blog/copyright-notices-in-open-source-software-projects/
- https://www.apache.org/legal/src-headers.html
- https://www.apache.org/foundation/license-faq.html
- https://infra.apache.org/licensing-howto.html
- https://www.apache.org/licenses/LICENSE-2.0

**Comment by kenji-miyake** [comment]
I think we can refer to the `iceoryx`'s way as well. It looks nice.
https://github.com/eclipse-iceoryx/iceoryx/blob/master/NOTICE.md
https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#header

**Comment by kenji-miyake** [comment]
My proposal:

### For new files

Rule:

- Prepare `NOTICE.md` and use `Copyright yyyy The Autoware Contributors.`.

Rationale:

- As LF says, We don't want to pay a lot of maintenance costs for updating copyright notations.

### For existing files

Rule:

- Accept the as-is style.
- We can change the copyright notation to `Copyright yyyy The Autoware Contributors.` if we can agree with the original authors to do so.

Rationale:

- Since we'll clean up the architecture for Autoware Core, we don't have to care about the existing Universe code so much.
- (I guess) We can't change the copyright notations without some agreements with the original authors.

### For all files

Rule:

- Add `SPDX-License-Identifier`.
- Will accept any other proposals in the future.

Rationale:

- SPDX is useful for automatically analyzing licenses.
- Since we are not legal professionals, there are a lot of things we don't know.

**Comment by kenji-miyake** [comment]
@xmfcx @kmiya What do think about this?

**Comment by kenji-miyake** [comment]
> (I guess) We can't change the copyright notations without some agreements with the original authors.

For this, I think it's a good idea to agree with people who want to write their names to `NOTICE.md`, that "if you want to write your name here, you have to remove your name from each Copyright notation or agree that the maintainers will remove them.", how about this?

**Comment by LalithVipulananthan** [comment]
From looking at the Apache examples given, they all say "Copyright yyyy The Apache Foundation" rather than "The Apache Contributors".

Is there some reason why we cannot say `Copyright yyyy The Autoware Foundation` ?

**Comment by kenji-miyake** [comment]
@LalithVipulananthan (Although I'm not sure I'm right...)

> From looking at the Apache examples given, they all say "Copyright yyyy The Apache Foundation" rather than "The Apache Contributors".

The ASF uses `Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.`.
https://www.apache.org/legal/src-headers.html

I guess why they do so is because they sign a CLA. (But I'm not sure.)

> Is there some reason why we cannot say Copyright yyyy The Autoware Foundation ?

I feel if we use `The Autoware Foundation` then it seems the AWF has the copyright.
But actually, since we don't use CLA and only use DCO instead, I think the copyright will remain with the original author, so `The Autoware Foundation` isn't correct.

**Comment by kenji-miyake** [comment]
TSC members will talk about this issue.
https://gitlab.com/autowarefoundation/autoware-foundation/-/issues/204

**Comment by kenji-miyake** [comment]
@filiperinaldi Thank you for your information.
Did you recommend replacing the `NOTICE` file with `CONTRIBUTORS.md`? Just showing another way?

**Comment by kenji-miyake** [comment]
The PR has moved from #29 to https://github.com/autowarefoundation/autoware-documentation/pull/44.

**Comment by kenji-miyake** [comment]
As https://github.com/autowarefoundation/autoware-documentation/pull/44 is merged, I'll close this issue.

However, everyone can reopen this and propose a change if necessary.
