### ISSUE TITLE
Add Ccache into docker image to speed up recompilation

### ISSUE THREAD

**Issue by brkay54** [autowarefoundation/autoware#321]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

In autoware documentation page, [Ccache](https://ccache.dev/) is recommended to speed up recompilation. See [here](https://autowarefoundation.github.io/autoware-documentation/latest/how-to-guides/advanced-usage-of-colcon/#using-ccache). 

### Purpose

- Add Ccache into docker image to speed up recompilation.

### Possible approaches

- Adding Ccache in Ansible.

**Comment by brkay54** [comment]
@kenji-miyake Should we add Ccache into docker image? What do you think?

**Comment by kenji-miyake** [comment]
@brkay54 Yes, I think it's possible. Could you send a PR like plotjuggler?
