### ISSUE TITLE
resolve libzmqpp-dev package in Ubuntu 22.04

### ISSUE THREAD

**Issue by hakuturu583** [autowarefoundation/autoware#351]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

scenario_simulator_v2 depends on [libzmqpp-dev package](https://packages.ubuntu.com/focal/libzmqpp-dev) in ubuntu, this package supports in focal but not supported in jammy.
In order to support humble and ubuntu jammy (22.04), we have to resolve this dependency.

### Purpose

Support humble and ubuntu jammy.

### Possible approaches

adding [zmqpp_vendor package](https://github.com/tier4/zmqpp_vendor) in simulator.repos file.
I already made a draft pull-request for this approach. #350

### Definition of done

Resolve zmqpp dependency in ROS2 humble and Ubuntu Jammy(22.04).

**Comment by wep21** [comment]
I think we can close this issue now that #350 is closed.
