### ISSUE TITLE
Docker instructions for multiple terminal usage

### ISSUE THREAD

**Issue by angry-crab** [autowarefoundation/autoware#80]
I'm wondering if there is any `cmd` existing in `universe` such that we could enter a specific docker container from another terminal. For example, when we were using `ade` in `Auto`, if an environment has been created, we can simply type `ade enter` from another terminal. I understand that we could use `docker exec --it container id` to enter the same image from another terminal. It seems that when I was using `rocker`, the container was created on the fly without a tag. I think it would be good to have some other simple `cmd` as `ade` does to enter the created container rather than copy and paste an temporary id.

**Comment by kenji-miyake** [comment]
@angry-crab I think you can do it by this.

```sh
# Terminal 1
rocker --name autoware ghcr.io/autowarefoundation/autoware-universe:latest

# Terminal 2
docker exec -it autoware /bin/bash
```

![image](https://user-images.githubusercontent.com/31987104/156709267-c9d625c0-c81e-4d36-9583-a88d515565b2.png)

**Comment by kenji-miyake** [comment]
You can send pull requests and update documents.

Around here?
- https://github.com/autowarefoundation/autoware/blob/main/docker/README.md
- https://github.com/autowarefoundation/autoware-documentation/pull/28

Or you can guide a new how-to guide page like this.
- https://github.com/autowarefoundation/autoware-documentation/pull/27

**Comment by angry-crab** [comment]
> You can send pull requests and update documents.
> 
> Around here?
> 
> * https://github.com/autowarefoundation/autoware/blob/main/docker/README.md
> * [docs: add tutorials autoware-documentation#28](https://github.com/autowarefoundation/autoware-documentation/pull/28)
> 
> Or you can guide a new how-to guide page like this.
> 
> * [docs: add advanced usage of colcon autoware-documentation#27](https://github.com/autowarefoundation/autoware-documentation/pull/27)

Thanks! I'll add it to the doc.

**Comment by angry-crab** [comment]
Close since it it no longer needed.
